# Generated by Django 4.1.5 on 2023-03-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProAdditional',
        ),
    ]
