# Generated by Django 4.1.5 on 2023-03-11 13:04

import annonces.enums
import annonces.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outil', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=annonces.enums.AnnonceTYPE['Offre'])),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='categorie name')),
                ('image', models.ImageField(blank=True, upload_to='media/categorie/')),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_name', models.CharField(max_length=255, unique=True, verbose_name='wilaya name')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=200)),
                ('ville_arrive', models.CharField(max_length=200)),
                ('date_depart', models.DateField(default=False)),
                ('date_arrive', models.DateField(default=False)),
                ('description', models.TextField(blank=True, default=' ')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.voyage_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_modele', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('puissance_fiscale', models.CharField(max_length=200)),
                ('boite_vitasses', models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], max_length=200)),
                ('Nombre_portes', models.IntegerField()),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('etat', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='outil.etat')),
                ('marque', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='outil.vehicle_marque')),
                ('modele', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='outil.vehicle_modele')),
                ('origine', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='outil.origine')),
                ('type_carburant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.type_carburants')),
            ],
        ),
        migrations.CreateModel(
            name='Top_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.etat')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.telephone_marque')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.telephone_model')),
                ('stockage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outil.stockage')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='categorie name')),
                ('image', models.ImageField(blank=True, upload_to='media/subcategorie/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='annonces.category')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=False)),
                ('lng', models.FloatField(default=False)),
                ('annonce', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Immobilier_plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerces_nombre', models.IntegerField()),
                ('commerces_trajet', models.IntegerField()),
                ('cafe_nombre', models.IntegerField()),
                ('cafe_trajet', models.IntegerField()),
                ('sport_nombre', models.IntegerField()),
                ('sport_trajet', models.IntegerField()),
                ('sante_nombre', models.IntegerField()),
                ('sante_trajet', models.IntegerField()),
                ('transport_nombre', models.IntegerField()),
                ('transport_trajet', models.IntegerField()),
                ('ecole_nombre', models.IntegerField()),
                ('ecole_trajet', models.IntegerField()),
                ('service_nombre', models.IntegerField()),
                ('service_trajet', models.IntegerField()),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambres', models.IntegerField()),
                ('salle_bain', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('surface', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('frais_syndic', models.CharField(max_length=200)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/annonce', validators=[annonces.validators.file_size])),
                ('annonce', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Commune name')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilaya', to='annonces.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire', to='annonces.annonce')),
                ('gest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.gest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.commune'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.subcategory'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
