# Generated by Django 4.1.5 on 2023-03-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='type',
        ),
    ]
